### ISSUE TITLE
Add open socket limiting support per service

### ISSUE THREAD

**Issue by schmidtw** [Comcast/webpa-common#244]
Ideally, we'd like to limit the number of open sockets per service in addition to the total number.  It would be great if the code present could be altered a bit to enable this.

**Comment by johnabass** [comment]
You can already limit connections via `maxConnections` per `http.Server` through configuration.  Are we wanting more granular control?

**Comment by johnabass** [comment]
Closing this issue, since it's been a feature for quite some time.
