### ISSUE TITLE
Add configurable Zookeeper or Consul Support

### ISSUE THREAD

**Issue by schmidtw** [Comcast/webpa-common#245]
It would be great to be able to use either Consul or Zookeeper via configuration for the server coordination.

**Comment by Symbianx** [comment]
@schmidtw is this referring to environment variables? 
We have successfully changed the port that Petasos listens on with environment variables but we are unable to change the Zookeeper endpoint.
It is blocking us since we want to configure everything with env variables.

**Comment by johnabass** [comment]
We have added configurable zookeeper vs consul support.  It's configurable via file or environment variable (or both).  See https://github.com/spf13/viper
