### ISSUE TITLE
ErrorDeviceClosed result in a 500 response code

### ISSUE THREAD

**Issue by schmidtw** [Comcast/webpa-common#310]
The `ErrorDeviceClosed` error results in a `500` response code which means there was an internal server error.  I think this is not the right code.

If the request has not been sent to the device, the error code should be `404` if the device was not there the instant the sending of the message was attempted.

If the request has been sent & the device disconnected mid-flight, we should probably define a new error code (`540`?) or use `504` to indicate that the transaction may have made it to the device, but the outcome is unknown due to a disconnection

Code of interest:
https://github.com/Comcast/webpa-common/blob/29d8d92a5b112b81d5d7b2dc4ad82180468598a0/device/device.go#L194

**Comment by johnabass** [comment]
Addressed by: https://github.com/Comcast/webpa-common/pull/314
